//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFClient.WCFServiceRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCFServiceRef.IServiceBookParser")]
    public interface IServiceBookParser {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookParser/CountUniqueWords", ReplyAction="http://tempuri.org/IServiceBookParser/CountUniqueWordsResponse")]
        System.Collections.Generic.Dictionary<string, long> CountUniqueWords(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBookParser/CountUniqueWords", ReplyAction="http://tempuri.org/IServiceBookParser/CountUniqueWordsResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, long>> CountUniqueWordsAsync(string xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceBookParserChannel : WCFClient.WCFServiceRef.IServiceBookParser, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceBookParserClient : System.ServiceModel.ClientBase<WCFClient.WCFServiceRef.IServiceBookParser>, WCFClient.WCFServiceRef.IServiceBookParser {
        
        public ServiceBookParserClient() {
        }
        
        public ServiceBookParserClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceBookParserClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBookParserClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceBookParserClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, long> CountUniqueWords(string xml) {
            return base.Channel.CountUniqueWords(xml);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, long>> CountUniqueWordsAsync(string xml) {
            return base.Channel.CountUniqueWordsAsync(xml);
        }
    }
}
